"use client";

import { useEffect, useRef, useState } from "react";
import { Play, Pause, Volume2, Maximize2, SkipForward } from "lucide-react";
import Image from "next/image";

export default function Demo() {
  const sectionRef = useRef<HTMLDivElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("revealed");
          }
        });
      },
      { threshold: 0.1 }
    );

    const reveals = sectionRef.current?.querySelectorAll(".reveal");
    reveals?.forEach((el) => observer.observe(el));

    return () => observer.disconnect();
  }, []);

  // Simulated progress animation
  useEffect(() => {
    if (isPlaying && progress < 65) {
      const timer = setTimeout(() => setProgress((p) => p + 0.5), 50);
      return () => clearTimeout(timer);
    }
    if (progress >= 65) {
      setIsPlaying(false);
    }
  }, [isPlaying, progress]);

  return (
    <section
      id="demo"
      ref={sectionRef}
      className="relative py-32 overflow-hidden"
    >
      {/* Background glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[600px] rounded-full bg-indigo-100/30 blur-[150px]" />

      <div className="relative z-10 mx-auto max-w-5xl px-6 lg:px-8">
        {/* Section header */}
        <div className="reveal mx-auto max-w-2xl text-center mb-16">
          <span className="inline-block mb-4 text-sm font-medium text-indigo-600 tracking-wider uppercase">
            Preview
          </span>
          <h2 className="font-[family-name:var(--font-inter)] text-4xl font-bold text-gray-900 sm:text-5xl tracking-tight">
            See It In <span className="gradient-text">Action</span>
          </h2>
          <p className="mt-6 text-lg text-gray-500 leading-relaxed">
            Watch how Manima transforms a simple prompt into a beautifully
            animated educational video.
          </p>
        </div>

        {/* Video player mock */}
        <div className="reveal">
          <div className="relative group rounded-3xl overflow-hidden shadow-2xl shadow-indigo-200/30 border border-gray-200/60 bg-white p-1">
            {/* Gradient border glow on hover */}
            <div className="absolute -inset-1 rounded-3xl bg-gradient-to-r from-violet-400/10 via-indigo-400/10 to-blue-400/10 blur-sm opacity-0 group-hover:opacity-100 transition-opacity duration-700" />

            <div className="relative rounded-[1.25rem] overflow-hidden bg-gray-950">
              {/* Top bar */}
              <div className="flex items-center gap-3 px-5 py-3 bg-gray-900 border-b border-gray-800">
                <div className="flex gap-1.5">
                  <span className="h-3 w-3 rounded-full bg-red-500/80" />
                  <span className="h-3 w-3 rounded-full bg-yellow-500/80" />
                  <span className="h-3 w-3 rounded-full bg-green-500/80" />
                </div>
                <div className="flex-1 flex justify-center">
                  <span className="text-xs text-gray-400 bg-gray-800 px-4 py-1 rounded-full">
                    Photosynthesis Process — Generated by Manima AI
                  </span>
                </div>
              </div>

              {/* Video content area */}
              <div className="relative aspect-video">
                <Image
                  src="/demo-preview.png"
                  alt="AI-generated educational video showing photosynthesis process"
                  fill
                  className="object-cover"
                  priority
                />

                {/* Play overlay */}
                {!isPlaying && progress === 0 && (
                  <div className="absolute inset-0 flex items-center justify-center bg-black/30">
                    <button
                      onClick={() => setIsPlaying(true)}
                      className="flex h-20 w-20 items-center justify-center rounded-full bg-white/15 backdrop-blur-xl border border-white/25 hover:bg-white/25 transition-all duration-300 hover:scale-110"
                    >
                      <Play
                        size={32}
                        className="text-white ml-1"
                        fill="white"
                      />
                    </button>
                  </div>
                )}
              </div>

              {/* Controls bar */}
              <div className="px-5 py-4 bg-gray-900 border-t border-gray-800">
                {/* Progress bar */}
                <div className="mb-3 h-1 w-full rounded-full bg-gray-700 overflow-hidden cursor-pointer">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-violet-500 to-indigo-500 transition-all duration-100"
                    style={{ width: `${progress}%` }}
                  />
                </div>

                {/* Controls */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <button
                      onClick={() => {
                        if (progress >= 65) setProgress(0);
                        setIsPlaying(!isPlaying);
                      }}
                      className="text-gray-400 hover:text-white transition-colors"
                    >
                      {isPlaying ? (
                        <Pause size={18} />
                      ) : (
                        <Play size={18} />
                      )}
                    </button>
                    <button className="text-gray-400 hover:text-white transition-colors">
                      <SkipForward size={18} />
                    </button>
                    <button className="text-gray-400 hover:text-white transition-colors">
                      <Volume2 size={18} />
                    </button>
                    <span className="text-xs text-gray-500">
                      {formatTime(progress)} / 3:24
                    </span>
                  </div>
                  <button className="text-gray-400 hover:text-white transition-colors">
                    <Maximize2 size={18} />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function formatTime(progress: number) {
  const totalSeconds = Math.floor((progress / 100) * 204); // 3:24 = 204 seconds
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${seconds.toString().padStart(2, "0")}`;
}
