-- Migration: Create videos and scenes tables for Agentic AI Video Generation
-- This migration creates the core database schema for tracking video generation requests
-- and their individual scenes through the agentic workflow.

-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- Enable Vector extension for RAG (Retrieval Augmented Generation)
create extension if not exists vector;

-- ============================================================================
-- VIDEOS TABLE
-- Stores video generation requests and their current status
-- ============================================================================
create table if not exists public.videos (
    id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) on delete cascade not null,
    prompt text not null,
    status text default 'planning' check (status in (
        'planning',           -- Initial planning phase
        'scripting',          -- Script generation in progress
        'waiting_approval',   -- Waiting for user to approve scripts
        'generating',         -- Manim code generation in progress
        'rendering',          -- Video rendering in progress
        'stitching',          -- Combining video segments
        'completed',          -- Successfully completed
        'failed'              -- Failed at some stage
    )),
    syllabus_doc_path text,           -- Path to uploaded PDF in Supabase Storage
    final_video_url text,             -- URL to final stitched video
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Add RLS (Row Level Security) policies for videos
alter table public.videos enable row level security;

-- Users can only see their own videos
create policy "Users can view own videos"
    on public.videos for select
    using (auth.uid() = user_id);

-- Users can create their own videos
create policy "Users can create own videos"
    on public.videos for insert
    with check (auth.uid() = user_id);

-- Users can update their own videos
create policy "Users can update own videos"
    on public.videos for update
    using (auth.uid() = user_id);

-- ============================================================================
-- SCENES TABLE
-- Stores individual scenes generated by the Planner/Script agents
-- ============================================================================
create table if not exists public.scenes (
    id uuid primary key default uuid_generate_v4(),
    video_id uuid references public.videos(id) on delete cascade not null,
    scene_order int not null,
    narration_script text,            -- What the narrator says
    visual_plan text,                 -- Description of visuals for Manim
    manim_code text,                  -- Generated Manim Python code
    is_rendered boolean default false,
    error_log text,                   -- Error messages for self-correction agent
    video_segment_url text,           -- URL to rendered scene video
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    
    -- Ensure unique scene order per video
    unique(video_id, scene_order)
);

-- Add RLS policies for scenes
alter table public.scenes enable row level security;

-- Users can view scenes of their own videos
create policy "Users can view scenes of own videos"
    on public.scenes for select
    using (
        exists (
            select 1 from public.videos
            where videos.id = scenes.video_id
            and videos.user_id = auth.uid()
        )
    );

-- Users can create scenes for their own videos
create policy "Users can create scenes for own videos"
    on public.scenes for insert
    with check (
        exists (
            select 1 from public.videos
            where videos.id = scenes.video_id
            and videos.user_id = auth.uid()
        )
    );

-- Users can update scenes of their own videos
create policy "Users can update scenes of own videos"
    on public.scenes for update
    using (
        exists (
            select 1 from public.videos
            where videos.id = scenes.video_id
            and videos.user_id = auth.uid()
        )
    );

-- ============================================================================
-- INDEXES
-- ============================================================================
create index if not exists idx_videos_user_id on public.videos(user_id);
create index if not exists idx_videos_status on public.videos(status);
create index if not exists idx_scenes_video_id on public.scenes(video_id);
create index if not exists idx_scenes_order on public.scenes(video_id, scene_order);

-- ============================================================================
-- UPDATED_AT TRIGGER
-- Automatically update the updated_at timestamp on row changes
-- ============================================================================
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger on_videos_updated
    before update on public.videos
    for each row execute function public.handle_updated_at();

create trigger on_scenes_updated
    before update on public.scenes
    for each row execute function public.handle_updated_at();
